### ISSUE TITLE
What file do I need? 

### ISSUE THREAD

**Issue by freynewton** [raw-lab/NFixDB#1]
I am just trying to get my head around the similarities/concurrences of NFixDB and PICRUSt2. 
I intend to create a dataset of projected/expected expression/abundance of nifH among my soil samples give their 16S sequencing data. 
Which files should be used as the "functional abundance table (tabular)" for the PICRUSt2 workflow? Is this necessary or can this all be done using NFixDB? 
Thank you!

**Comment by raw-lab** [comment]
Good evening Frey,

So, we are a bit unsure by your question. NFixDB is a database of HMMs and sequences based on whole genome analysis which includes nifDHK and their alternatives anf/vnfDHK. 

PICRUST2 predicts functions based on 16S 
sequences. NFixDB doesn't do this. 

NFixDB is for searching shotgun metagenomic/metatranscriptomes using hmmer. 

It could also be used for designing primers with our other tool DeGenPrime. 

If you have nifH amplicon data we have a beta code for that called therion. 

Let us know?

Many thanks,
RAW lab

**Comment by MicoNick** [comment]
Good day dear developers!

I would like to estimate the level of nitrogen fixation gene content in my metagenomic samples

I have metagenomes both as nucleotide sequence fasta files and as amino acid fasta sequences

Could you please advise if there is any brief instruction on how to use it for my purposes?

Which of the files should I use as a database, e.g. for DIAMOND or BLAST searches for homologous sequences?

And also a question - what is the NFixDB-R2.db file and why DIAMOND gives an error that it is not a blast database when trying to use it as a database?

Translated with DeepL.com (free version)

**Comment by raw-lab** [comment]
Are they shotgun metagenomic samples or amplicon nifH samples? 

NFixDB is not a blast or diamond database. It's a HMM based database. 

NFixDB is fully functional and available in our tool MetaCerberus which can take nucleic or amino acid fasta sequences. 

MetaCerberus 
www.github.com/raw-lab/metacerberus

Let us know?

Many thanks,
RAW Lab

**Comment by MicoNick** [comment]
These data files are shotgun metagenomic samples 
Do I need to tell it that I want to get data on the quantitative representation of nitrogen fixation genes in metagenomes?

**Comment by raw-lab** [comment]
You can run your samples with MetaCerberus. It will count the number of nitrogen fixation genes. There is a tutorial that provides scripts to run DESeq2,  gage, and pathview for pathway enrichment quantitation. 

Let us know?

Closing for now. Give MetaCerberus a try.

**Comment by MicoNick** [comment]
Can I ask you to send me a link to this tutorial? 
Am I correct in understanding that I can submit raw readings to Metacerberus for input?

**Comment by raw-lab** [comment]
https://metacerberus.readthedocs.io/en/latest/tutorial1.html

Also, the readme has lots of instructions

**Comment by MicoNick** [comment]
Thanks a lot!
I'll try to use it

And I have last question
Can I get an information about antibiotics resistance genes and phosphorus cycle genes If I'm using this software?

**Comment by raw-lab** [comment]
Yes, of course. KOs for phosphorus genes. AMRfinder hmms are also present.

**Comment by MicoNick** [comment]
So this information will be in the form of KO numbers? 
Or will there be reports for each class of genes?

**Comment by raw-lab** [comment]
Yes in the final folder.

**Comment by MicoNick** [comment]
Many thanks! 🫶
Have a great day)))
