### ISSUE TITLE
Workflow to run NFixDB

### ISSUE THREAD

**Issue by anilchauhanhp9** [raw-lab/NFixDB#2]
Hi,

Thank you for creating the database.

Can you provide a workflow for installing or running the analysis using this database? I have genome fasta files and need to look for nitrogen-fixing genes in the genome. I do not find any workflow for using this tool/database on genomic data files.

Thank you.

**Comment by raw-lab** [comment]
This is just the HMM databases. Our tool MetaCerberus is the start to finish workflow to run the HMMs from NFixDB

github.com/raw-lab/metacerberus 

Let us know if you need any further help?

**Comment by anilchauhanhp9** [comment]
Hi,

Thank you for your quick response.

I downloaded the MetaCerberus tool and the databases attached to it. The tool only downloaded KOFam, CAZy, PHROG, VOG, PVOG, PFAM, TIGRFAM, AMRFinder, PGAP and GVDB databases. NFixDB and other remaining databases mentioned in the MetaCerberus readme file were downloaded. DO I have to download them separately?

**Comment by decrevi** [comment]
Hello,

NFixDB should now be live. You can run the command `metacerberus.py --download NFixDB` to download the individual database.

You can then use the flag `--hmm NFixDB` if you want to run only the NFixDB HMMs on your dataset.

Do let us know if you have any issues!
Thank you,
-Jose

**Comment by raw-lab** [comment]
Thank you for using NFixDB and MetaCerberus! If you need something custom or have a specific issue please let us know. We will be here to help you out. 

Closing for now.
